### PR TITLE
feat: initial nuxt devtools setup

### PR DESCRIPTION
**Pull request by arashsheyda**
right now this PR it only adds a tab to nuxt devtools.

- [ ] detect the current used fonts and show them in devtools tab

### CODE REVIEW

**Comment by BobTheShoplifter** [comment]
Great release

**Comment by danielroe** [comment]
no idea why this was closed....

**Comment by arashsheyda** [comment]
:D should I push the updates? also do you think we should refactor the rpc in the client to composables? or you want to have everything in `app.vue` ?

**Comment by danielroe** [comment]
please do push the updates, and feel free to refactor.

you will need to reopen the PR - I imagine it got closed somehow when I open-sourced the repo?

**Comment by arashsheyda** [comment]
@danielroe Oh yes, it seems I don't have an re-open button, can you do it or should I open a new one 😄 sorry

**Comment by danielroe** [comment]
Weirdly your fork has vanished (to me) so I can't reopen it.

**Pull request closed without merging**
