### PR TITLE
feat(provider): provide options to disable `addLocalFallbacks`

### PR DESCRIPTION
**Pull request by qwerzl**
This PR adds a `disableLocalFallbacks` option in `fonts.defaults`.

### CODE REVIEW

**Comment by danielroe** [comment]
I think the first step is to ensure we are generating correct name for the local font file. Adding font weight (e.g. 'Arial Bold' rather than just 'Arial') is likely the correct step.

**Comment by qwerzl** [comment]
@danielroe I agree. I've opened #71 for that.

**Comment by danielroe** [comment]
Do you think we still need this following #71?

**Comment by qwerzl** [comment]
Hmm, I don't think so. It should be able to match font weights correctly now.

**Pull request closed without merging**
