### PR TITLE
feat: support variable axis

### PR DESCRIPTION
**Pull request by qwerzl**
This PR adds support for variable font axis. It's quite sad that AFAIK only Google provides this level of configuration.

### CODE REVIEW

**Comment by qwerzl** [comment]
Hi @danielroe, the type issues are fixed and I've added tests for Recursive. Sorry I didn't see the failed checks yesterday to it took some time.

**Review by danielroe — COMMENTED** [review]
Rather than creating a new property (`variableAxis`) I think we ought to try to use `font-variation-settings`/`variationSettings` which could take a string or an object of dimension/value.

We could then use this to render both the font-face and also _detect_ the required variations from CSS directly rather than require it to be configured.

**Comment by qwerzl** [comment]
@danielroe I've also thought about this, but I'm not sure whether `font-variation-settings` allows a range of values.

**Comment by qwerzl** [comment]
Now that unifont is released, I think this PR should be closed. 

For fine-grained variable axis control of providers other than `google`, I'm thinking about a variable axis subsetter built into unifont once [klippa](https://github.com/googlefonts/fontations/tree/main/klippa/src) supports it.

**Comment by danielroe** [comment]
we could also open again on unifont - for nuxt/fonts i wanted to think if there was a way to make this zero config but i know it’s taken too long 🙈

**Pull request closed without merging**
